### PR TITLE
Reflect the fact that atom-dark is no longer the default

### PR DESCRIPTION
**Pull request by AgentAntelope**
This changed in atom v0.188.0

### CODE REVIEW

**Comment by simurai** [comment]
@AgentAntelope Right! Thank you.

**Comment by AgentAntelope** [comment]
It's still my favourite though! :shrug:

**Comment by simurai** [comment]
:+1: It will keep being bundled.

**Comment by AgentAntelope** [comment]
Awesome!

Is a similar change needed over at https://github.com/atom/atom-dark-ui ?

**Comment by simurai** [comment]
Actually.. yes. And I guess also for the light themes: https://github.com/atom/atom-light-ui + https://github.com/atom/atom-light-syntax. If you feel like it. :bow:

**Pull request merged**
